lint-composer-validate:
  image:
    name: php:8.3
  interruptible: true
  parallel:
    matrix:
      - WORKING_DIR:
          - modules/core
          - modules/storage
          - website
  rules:
    - changes:
        paths:
          - "$WORKING_DIR/composer.*"
  script:
    - curl -sS https://getcomposer.org/installer | php
    - >
      php composer.phar validate
      --working-dir="$WORKING_DIR"
      --strict
      --no-check-version

lint-editorconfig:
  image:
    name: mstruebing/editorconfig-checker:2.7.2
  interruptible: true
  script:
    - ec -version
    - ec -verbose
