services:
    _defaults:
        autowire: true
        autoconfigure: true

    Quintolin\Storage\Repository\:
        resource: '../../../modules/storage/src/Repository/'

    Quintolin\Storage\Query\:
        resource: '../../../modules/storage/src/Query/'

    Quintolin\Storage\Repository\ReleaseNoteRepository:
        arguments:
            $projectDir: '%kernel.project_dir%/data/release-notes'
