twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        app_clock: '@Psr\Clock\ClockInterface'
        page_context: '@App\Twig\PageContext'

when@test:
    twig:
        strict_variables: true
