twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    globals:
        app_clock: '@Psr\Clock\ClockInterface'
        app_page_title: '@App\Twig\PageTitle'

when@test:
    twig:
        strict_variables: true
