<?php

declare(strict_types=1);

/**
 * Returns the importmap for this application.
 *
 * - "path" is a path inside the asset mapper system. Use the
 *     "debug:asset-map" command to see the full list of paths.
 *
 * - "entrypoint" (JavaScript only) set to true for any module that will
 *     be used as an "entrypoint" (and passed to the importmap() Twig function).
 *
 * The "importmap:require" command can be used to add new entries to this file.
 *
 * This file has been auto-generated by the importmap commands.
 */
return [
    'website' => [
        'path' => './assets/js/website.js',
        'entrypoint' => true,
    ],
    'es-module-shims' => [
        'version' => '1.8.2',
    ],
    '@popperjs/core' => [
        'version' => '2.11.8',
    ],
    'bootstrap' => [
        'version' => '5.3.2',
    ],
    'bootstrap/dist/css/bootstrap.min.css' => [
        'version' => '5.3.2',
        'type' => 'css',
    ],
    '@fontsource/freckle-face' => [
        'version' => '5.0.18',
    ],
    '@fontsource/freckle-face/index.min.css' => [
        'version' => '5.0.18',
        'type' => 'css',
    ],
];
