name: Validate Composer Files
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  validate:
    name: Validate `${{ matrix.dir }}`
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir:
          - modules/core
          - modules/storage
          - website
    steps:
      - uses: actions/checkout@v4
      - name: Validate files
        run: composer validate --working-dir="${{ matrix.dir }}" --strict --no-check-version
